server:
  port: 8080

springdoc:
  packagesToScan: com.impactzb.productpricecalculator.api
  pathsToMatch: /product/**

management:
  endpoint:
    health:
      probes:
        enabled: true

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
